Added IDE section using codesandbox
arshadpatel/codeX100 pull request #49
Opened 2024-10-06 07:36 UTC by 0-SiddharthJoshi-0

2024-10-06 08:43 UTC, arshadpatel requested changes
I have reviewed your changes and I liked it but we are planning for simple page where the user can select the language and can execute the program easily... for example online GDB, programmiz and etc

2024-10-06 12:22 UTC, 0-SiddharthJoshi-0 commented on frontend/IDE.html
> +        <iframe id="codeFrame" src="https://www.jdoodle.com/c-online-compiler" width="100%" height="500px" frameborder="0"></iframe>
I have changed the IDE now you can select which programming language you want to use, by using a searching in right next to execute button.

2024-10-06 12:25 UTC, 0-SiddharthJoshi-0 commented
I have changed the IDE as you requested .

2024-10-07 15:45 UTC, arshadpatel requested changes
Is there any other way instead of using sandbox... Because it is not looking good... As you can see there are two buttons of login one belongs to our website and other belongs to sandbox itself.

2024-10-11 17:25 UTC, 0-SiddharthJoshi-0 commented
I have tried using other IDE's but it makes page less responsive , and some of them show advertisements .

2024-10-11 17:27 UTC, 0-SiddharthJoshi-0 reviewed
.

2024-10-12 02:49 UTC, merged